# Generated by Django 3.0.8 on 2020-08-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title', 'category')},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('tag',)},
        ),
    ]
