# Generated by Django 3.0.8 on 2020-08-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProjectImage',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='ProjectTag',
            new_name='Tag',
        ),
    ]
