version: '3.8'

services:
  postgres:
    image: postgres:10.14-alpine
    volumes:
      - db_pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  base:
    build: .
    volumes:
      - .:/code
    depends_on:
      - postgres
    ports:
      - '80:80'
    env_file: .env
    environment:
      DEBUG_MODE: 'TRUE'
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:80']

volumes:
  db_pg:
    external:
      name: meetm_db_pg
